spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/medicore
    username: postgres
    password: hmax0705

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8090